### ISSUE TITLE
ReferereceError: Can't find variable: mathBox at b - first.js

### ISSUE THREAD

**Issue by jorgfinsv** [IDIAMath/moodle-qtype_stack#6]
Found through inspect element in browser when testing the program. 

![Image](https://user-images.githubusercontent.com/44703456/174760617-2caa0130-7fa7-4c43-ac83-1f3e225baec6.png)

Branch: 1-feature-3d-radio-question-subtype

**Comment by hgeorgsch** [comment]
I find references to mathBox in two files: ./amd/src/mathbox-bundle.js and ./amd/build/threedradio.min.js.map
Is there any reason to keep the mathbox-bundle?  Or could this be removed at this point?
The map file seems not to have been rebuilt.  It is strange if the map file keeps a reference when it has been removed from the javascript file.  Can you have a look at this?

**Comment by jorgfinsv** [comment]
I have deleted the mathbox-bundle file, it did not affect the error. The map-file still contains mathBox-references after rebuilding. The only reference to mathBox in ./amd/src/threedradio.js is in comments, one method name and as a parser-string, but I don't think this is the cause of this phenomenon.

**Comment by jorgfinsv** [comment]
Freshest commit is now pushed

**Comment by jorgfinsv** [comment]
I think everything is accounted for. Everything in build gets either modified or created automatically when amd builds the src-files. Everything in src is supposed to be there, and the only deleted file should mathbox-bundle. Compared to the content in its clone on the master-branch

**Comment by jorgfinsv** [comment]
https://jsxgraph.uni-bayreuth.de/wp/download/index.html says however that jsxgraph requires a css-file too. Could this be the cause?

**Comment by hgeorgsch** [comment]
How do you run the amd builder?  
The javascript interpreter should not read the CSS file. A missing CSS file may break the rendering, but it should not affect the script.
Try #7 first.

**Comment by jorgfinsv** [comment]
I tried including the css-file before, but not in amd. I integrated it with the already existing css-file in the root of the folder
