### ISSUE TITLE
Merge upstream changes (official STACK release) into 3d radio branch

### ISSUE THREAD

**Issue by hgeorgsch** [IDIAMath/moodle-qtype_stack#7]

**Comment by hgeorgsch** [comment]
When this is done, bugs #5 and #6 need to be reconfirmed.

**Comment by jorgfinsv** [comment]
Merged with master-branch and tested again. Bugs #5 and #6 are still there. I have sent a mail to the supplier of JSXGraph and told about the problems, hoping we can get some feedback from there.
